apiVersion: custompodautoscaler.com/v1
kind: CustomPodAutoscaler
metadata:
  name: cpa-cartservice
spec:
  template:
    spec:
      containers:
      - name: cpa-cartservice
        image: danielmapar/cpa:latest
        env:
          - name: MONGO_HOST
            value: "mongodb.default.svc.cluster.local"
          - name: MONGO_PORT
            value: "27017"
          - name: MONGO_DBNAME
            value: "cpa"
          - name: MONGO_USERNAME
            value: "root"
          - name: MONGO_PASSWORD
            value: "iRhrF6O0vp"
          - name: PROMETHEUS_URL
            value: "http://192.168.23.92:9090"
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cartservice
  config:
    - name: interval
      value: "10000"
