apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cpa-api-service-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-cpa-api-service
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cpa-api-service-vs
spec:
  hosts:
  - "*"
  gateways:
  - cpa-api-service-gateway
  http:
  - match:
    - uri:
        exact: /loadTests
    - uri:
        exact: /predictions
    - uri:
        exact: /setDeployments
    - uri:
        exact: /deployments
    - uri:
        exact: /setEquation
    - uri:
        exact: /equation
    - uri:
        exact: /createLoadTest
    route:
    - destination:
        host: cpa-api-service
        port:
          number: 5001
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: 
spec:
  host: cpa-api-service
  trafficPolicy:
    tls:
      mode: DISABLE
